server.port=8080
spring.application.name=cert-recommendation-server
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
spring.web.resources.static-locations=classpath:/static/
